### ISSUE TITLE
30122025

### ISSUE THREAD

**Issue by Joohangooi** [Joohangooi/Share#8]
Got it 👍
From your screenshot, you already have a DataSet coming back from backend, and now you want to create one ViewModel (VM) and pass it to the frontend.

I’ll assume this is ASP.NET (WebForms / MVC / Web API) since you’re using DataSet.

⸻

1️⃣ Create a ViewModel (VM)

Looking at your returned columns:

BOP_BROADPURP
BOP_PURP_CODE
BOP_PURPDESC
BOP_LASTEDITSTMP
BOP_LASTEDITBY
BOP_FTT_PURP_ID
BOP_PURPCODE
BOP_FTT_BROADPURP_ID

Create a VM like this:

public class FttPurposeVm
{
    public string BroadPurpose { get; set; }
    public int PurposeCode { get; set; }
    public string PurposeDesc { get; set; }
    public DateTime? LastEditTimestamp { get; set; }
    public string LastEditBy { get; set; }
    public int FttPurposeId { get; set; }
    public string PurpCode { get; set; }
    public int FttBroadPurposeId { get; set; }
}

⸻

2️⃣ Map DataSet → ViewModel

Assuming your data is in ds.Tables[0]:

DataSet ds = broadPurposeOfRemittanceBusiness
    .GetAllBroadFTTData(selectedParam, column, fromTable, where, groupBy, orderBy);

FttPurposeVm vm = null;

if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
{
    DataRow row = ds.Tables[0].Rows[0];

    vm = new FttPurposeVm
    {
        BroadPurpose = row["BOP_BROADPURP"]?.ToString(),
        PurposeCode = Convert.ToInt32(row["BOP_PURP_CODE"]),
        PurposeDesc = row["BOP_PURPDESC"]?.ToString(),
        LastEditTimestamp = row["BOP_LASTEDITSTMP"] == DBNull.Value 
            ? null 
            : Convert.ToDateTime(row["BOP_LASTEDITSTMP"]),
        LastEditBy = row["BOP_LASTEDITBY"]?.ToString(),
        FttPurposeId = Convert.ToInt32(row["BOP_FTT_PURP_ID"]),
        PurpCode = row["BOP_PURPCODE"]?.ToString(),
        FttBroadPurposeId = Convert.ToInt32(row["BOP_FTT_BROADPURP_ID"])
    };
}

⸻

3️⃣ Pass to Frontend (choose your pattern)

✅ If ASP.NET MVC

return View(vm);

In Razor:

@Model.PurposeDesc
@Model.BroadPurpose

⸻

✅ If Web API

return Ok(vm);

Frontend (JS):

response.data.purposeDesc
response.data.broadPurpose

⸻

✅ If WebForms

myUserControl.DataSource = new List<FttPurposeVm> { vm };
myUserControl.DataBind();

⸻

4️⃣ (Optional) If you expect multiple rows

Use List<FttPurposeVm> instead:

var list = ds.Tables[0].AsEnumerable()
    .Select(r => new FttPurposeVm
    {
        BroadPurpose = r["BOP_BROADPURP"].ToString(),
        PurposeCode = r.Field<int>("BOP_PURP_CODE"),
        PurposeDesc = r["BOP_PURPDESC"].ToString(),
        LastEditTimestamp = r.Field<DateTime?>("BOP_LASTEDITSTMP"),
        LastEditBy = r["BOP_LASTEDITBY"].ToString(),
        FttPurposeId = r.Field<int>("BOP_FTT_PURP_ID"),
        PurpCode = r["BOP_PURPCODE"].ToString(),
        FttBroadPurposeId = r.Field<int>("BOP_FTT_BROADPURP_ID")
    })
    .ToList();

⸻

TL;DR
	•	DataSet → ViewModel
	•	Do NOT pass DataSet directly to frontend
	•	Map once, frontend stays clean and stable

If you tell me:
	•	MVC / Web API / WebForms?
	•	Frontend is Razor / Angular / React / jQuery?

I can tailor it exactly to your stack.

**Comment by Joohangooi** [comment]
CreatePurposeOfRemitVM vm =
    ftt_purpose_dataset.Tables[0]
        .AsEnumerable()
        .Select(row => new CreatePurposeOfRemitVM
        {
            // ===== Parent VM fields =====
            SELECTED_BROAD_PURP_ID =
                row.Field<decimal?>("BOP_FTT_BROADPURP_ID"),

            SELECTED_BROAD_PURP_TEXT =
                row["BOP_PURPDESC"]?.ToString(),

            // ===== Nested object =====
            bOP_FTT_PURP = new BOP_FTT_PURP
            {
                BOP_FTT_PURP_ID =
                    row.Field<decimal?>("BOP_FTT_PURP_ID"),

                BOP_PURPCODE =
                    row["BOP_PURPCODE"]?.ToString(),

                BOP_PURPDESC =
                    row["BOP_PURPDESC"]?.ToString(),

                BOP_FTT_BROADPURP_ID =
                    row.Field<decimal?>("BOP_FTT_BROADPURP_ID"),

                BOP_LASTEDITBY =
                    row["BOP_LASTEDITBY"]?.ToString(),

                BOP_LASTEDITSTMP =
                    row.Field<DateTime?>("BOP_LASTEDITSTMP")
            }
        })
        .FirstOrDefault();

**Comment by Joohangooi** [comment]
<div class="row margin-top-10">
    <div class="form-group">
        <label class="control-label col-md-2">
            @Html.LabelFor(model => model.bOP_FTT_PURP.BOP_EFFECTIVEDATE)
        </label>

        <div class="col-md-9">
            @Html.EditorFor(
                model => model.bOP_FTT_PURP.BOP_EFFECTIVEDATE,
                new
                {
                    htmlAttributes = new
                    {
                        @class = "form-control",
                        required = "required",
                        placeholder = "Select Future Date",
                        @readonly = "readonly",
                        style = "cursor:pointer; background:white;"
                    }
                })

            
            @Html.ValidationMessageFor(
                model => model.bOP_FTT_PURP.BOP_EFFECTIVEDATE,
                "",
                new { @class = "text-danger d-block" })
        </div>
    </div>
</div>

**Comment by Joohangooi** [comment]
Alright, let’s force it, no theory 😄
If MVC + Bootstrap refuses to behave, we’ll hard-override the layout so the validation message must go to the next line.

Below are 3 guaranteed ways — start from Option 1, it works in 99% of cases.

⸻

✅ OPTION 1 (MOST RELIABLE): wrap validation in its own <div>

This bypasses Bootstrap inline behavior completely.

@Html.TextAreaFor(
    model => model.bOP_FTT_PURP.BOP_PURPDESC,
    new
    {
        @class = "form-control",
        required = "required",
        placeholder = "Enter FTT Purpose Description",
        maxlength = 100
    })

<div class="validation-row">
    @Html.ValidationMessageFor(
        model => model.bOP_FTT_PURP.BOP_PURPDESC,
        "",
        new { @class = "text-danger" })
</div>

Then add CSS (this is the key):

.validation-row {
    display: block;
    width: 100%;
    clear: both;
}

💥 This forces a new line, no matter what Bootstrap does.

⸻

✅ OPTION 2: override MVC validation CSS (simple & global)

MVC outputs this class automatically:

<span class="field-validation-error">...</span>

Force it globally:

.field-validation-error {
    display: block !important;
    clear: both;
    margin-top: 5px;
}

✔ Works for all fields
✔ No Razor changes needed

⸻

✅ OPTION 3: <br /> brute-force (not pretty, but works)

If you just want it working now:

@Html.TextAreaFor(model => model.bOP_FTT_PURP.BOP_PURPDESC)

<br />

@Html.ValidationMessageFor(
    model => model.bOP_FTT_PURP.BOP_PURPDESC,
    "",
    new { @class = "text-danger" })

I don’t recommend this long-term, but it will work immediately.

⸻

❌ What does NOT work (important)

These won’t help alone in Bootstrap forms:

d-block
<br class="clearfix">
span { display:block }  // without !important

Because .control-label, .form-group, or .help-inline overrides them.

⸻

✅ My recommendation (senior-dev answer)

Use Option 1 + CSS.
It’s clean, readable, Bootstrap-proof, and future-safe.

If you want, next I can:
	•	align error text exactly under textarea width
	•	show error only after submit
	•	add red border + shake animation 😄

Just tell me.

**Comment by Joohangooi** [comment]
function checkDuplicateCode() {
    var purposeCode = $("#BOP_PURPCODE").val();
    var url = rootDir + "FTTPurpose/PurposeCodeValidation/" + purposeCode;

    return $.getJSON(url)
        .then(function (res) {
            if (res.exists) {
                showDuplicatePopover("Purpose Code Exist");
                return false; // ❗ resolved value
            }
            return true;
        })
        .catch(function () {
            return false;
        });
}

**Comment by Joohangooi** [comment]
Perfect screenshot — the console error tells us exactly what’s wrong 👍
This is NOT your logic — it’s a jQuery version issue.

⸻

🔴 Root cause (100% confirmed)

You’re using jQuery 1.11.3:

jquery-1.11.3.js

In jQuery 1.x:

❌ .catch() does NOT exist
❌ .then() is not Promise/A+ compatible

That’s why you get:

Uncaught TypeError: $.getJSON(...).then(...).catch is not a function


⸻

✅ FIX #1 (BEST for jQuery 1.11): use .done() / .fail()

✔ Corrected checkDuplicateCode() (WORKS in jQuery 1.11)

function checkDuplicateCode(callback) {
    var purposeCode = $("#BOP_PURPCODE").val();
    var url = rootDir + "FTTPurpose/PurposeCodeValidation/" + purposeCode;

    $.getJSON(url)
        .done(function (res) {
            if (res) {
                showDuplicatePopover("Purpose Code Exist");
                callback(false); // ❌ stop
            } else {
                callback(true);  // ✅ allow
            }
        })
        .fail(function () {
            callback(false);
        });
}


⸻

✅ How to CALL it (this is critical)

You CANNOT return synchronously.
You must use a callback.

$("#next").on("click", function (e) {
    e.preventDefault();

    checkDuplicateCode(function (isValid) {
        if (!isValid) {
            return false;
        }

        // ✅ only continues if backend says OK
        CheckLock(pendingid, buttonid);
    });
});


⸻

✅ Popover helper (unchanged, works)

function showDuplicatePopover(message) {
    $("#next")
        .popover({
            html: true,
            placement: "bottom",
            container: "body",
            trigger: "manual",
            content: message
        })
        .popover("show")
        .on("blur hidden.bs.popover", function () {
            $(this).popover("destroy");
        });
}


⸻

❌ What you MUST NOT do (with jQuery 1.x)

❌ .catch()
❌ return false inside done()
❌ Expecting checkDuplicateCode() to return boolean
❌ async: false (blocks browser, deprecated)

⸻

🧠 Mental rule (remember this forever)

AJAX result can only be used INSIDE callback (or Promise)

Since you’re on legacy jQuery, callback pattern is the correct solution.

⸻

✅ Alternative (if you can upgrade later)

If someday you move to jQuery 3.x, then you can use:

$.getJSON(url)
  .then(...)
  .catch(...)

But today, your fix is .done() / .fail().

⸻

TL;DR

✔ Error is because jQuery 1.11 has no .catch()
✔ Use callback + done/fail
✔ Your backend logic is fine
✔ Your popover logic is fine

If you want next, I can:
	•	refactor this into a jQuery Validate remote rule
	•	debounce the check (avoid hitting backend too often)
	•	convert this into async/await (if you upgrade)

Just tell me 👌

**Comment by Joohangooi** [comment]
function showDuplicatePopover(message) {
    var $btn = $("#next");

    if ($btn.data('bs.popover')) {
        $btn.popover("dispose");
    }

    $btn.popover({
        html: true,
        placement: "bottom",
        container: "body",
        trigger: "manual",
        content: message
    });

    $btn.popover("show");

    $btn.one('hidden.bs.popover', function () {
        $btn.popover("dispose");
    });
}

**Comment by Joohangooi** [comment]
function showDuplicatePopover(message) {
    var $btn = $("#next");

    if ($btn.data('bs.popover')) {
        $btn.popover("dispose");
    }

    $btn.popover({
        html: true,
        placement: "bottom",
        container: "body",
        trigger: "manual",
        content: message
    });

    $btn.popover("show");

    $btn.one('hidden.bs.popover', function () {
        $btn.popover("dispose");
    });
}

**Comment by Joohangooi** [comment]
function checkDuplicateCode() {
    var purposeCode = $("#BOP_PURPCODE").val();
    var url = rootDir + "FTTPurpose/PurposeCodeValidation/" + purposeCode;

    $.getJSON(url)
        .done(function (res) {
            if (res.exists) {
                showDuplicatePopover("Purpose Code Exist");
                return; // ❌ STOP here, do NOT continue
            }

            // ✅ only proceed if NOT duplicate
            $("#btnSaveNext").trigger("click");
        })
        .fail(function () {
            alert("Validation service error");
        });
}
